#############################################################################
# Makefile for building: test
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  test.pro
# Template: app
# Command: /Users/apple/Applications/Qt/5.8/clang_64/bin/qmake -o Makefile test.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include/opencv -I/usr/local/include -I../../../Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I../../../Applications/Qt/5.8/clang_64/mkspecs/macx-clang -F/Users/apple/Applications/Qt/5.8/clang_64/lib
QMAKE         = /Users/apple/Applications/Qt/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = test1.0.0
DISTDIR = /Users/apple/projects/computer_vision/sxy1/.tmp/test1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS) -Wl,-rpath,/Users/apple/Applications/Qt/5.8/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/apple/Applications/Qt/5.8/clang_64/lib -L/Users/apple/projects/computer_vision/opencv/build/3rdparty/ippicv/ippicv_osx/lib/ -L/usr/local/lib -lopencv_cudabgsegm -lopencv_cudaobjdetect -lopencv_cudastereo -lopencv_shape -lopencv_stitching -lopencv_cudafeatures2d -lopencv_superres -lopencv_videostab -lopencv_cudaoptflow -lopencv_cudalegacy -lopencv_calib3d -lopencv_features2d -lopencv_objdetect -lopencv_highgui -lopencv_videoio -lopencv_photo -lopencv_imgcodecs -lopencv_cudawarping -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_video -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_cudaarithm -lopencv_core -lopencv_cudev -framework QtCore -framework DiskArbitration -framework IOKit 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		imgprofile.cpp \
		medianfilter.cpp 
OBJECTS       = main.o \
		imgprofile.o \
		medianfilter.o
DIST          = Makefile \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/qdevice.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/unix.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/mac.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/macx.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/clang.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/qconfig.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/link_pkgconfig.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/qt.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/resources.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/moc.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/lex.prf \
		test.pro imgprofile.h \
		public_lib.h \
		mytuple.h \
		medianfilter.h main.cpp \
		imgprofile.cpp \
		medianfilter.cpp
QMAKE_TARGET  = test
DESTDIR       = 
TARGET        = test


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: test.pro ../../../Applications/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf ../../../Applications/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/qdevice.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/unix.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/mac.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/macx.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/clang.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/qconfig.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/link_pkgconfig.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/qt.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/resources.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/moc.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		../../../Applications/Qt/5.8/clang_64/mkspecs/features/lex.prf \
		test.pro \
		../../../Applications/Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile test.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../../Applications/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/qdevice.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/device_config.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/common/unix.conf:
../../../Applications/Qt/5.8/clang_64/mkspecs/common/mac.conf:
../../../Applications/Qt/5.8/clang_64/mkspecs/common/macx.conf:
../../../Applications/Qt/5.8/clang_64/mkspecs/common/sanitize.conf:
../../../Applications/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf:
../../../Applications/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Applications/Qt/5.8/clang_64/mkspecs/common/clang.conf:
../../../Applications/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf:
../../../Applications/Qt/5.8/clang_64/mkspecs/qconfig.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/qt_config.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/toolchain.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/default_pre.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/default_post.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/link_pkgconfig.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/warn_on.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/qt.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/resources.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/moc.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/file_copies.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/exceptions.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/yacc.prf:
../../../Applications/Qt/5.8/clang_64/mkspecs/features/lex.prf:
test.pro:
../../../Applications/Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile test.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Applications/Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents imgprofile.h public_lib.h mytuple.h medianfilter.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp imgprofile.cpp medianfilter.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Applications/Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../Applications/Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp public_lib.h \
		mytuple.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/ml.hpp \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/shape.hpp \
		/usr/local/include/opencv2/shape/emdL1.hpp \
		/usr/local/include/opencv2/shape/shape_transformer.hpp \
		/usr/local/include/opencv2/shape/hist_cost.hpp \
		/usr/local/include/opencv2/shape/shape_distance.hpp \
		/usr/local/include/opencv2/stitching.hpp \
		/usr/local/include/opencv2/stitching/warpers.hpp \
		/usr/local/include/opencv2/stitching/detail/warpers.hpp \
		/usr/local/include/opencv2/core/cuda.hpp \
		/usr/local/include/opencv2/core/cuda_types.hpp \
		/usr/local/include/opencv2/core/cuda.inl.hpp \
		/usr/local/include/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/local/include/opencv2/stitching/detail/matchers.hpp \
		/usr/local/include/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/local/include/opencv2/stitching/detail/util.hpp \
		/usr/local/include/opencv2/stitching/detail/util_inl.hpp \
		/usr/local/include/opencv2/stitching/detail/camera.hpp \
		/usr/local/include/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/local/include/opencv2/stitching/detail/seam_finders.hpp \
		/usr/local/include/opencv2/stitching/detail/blenders.hpp \
		/usr/local/include/opencv2/superres.hpp \
		/usr/local/include/opencv2/superres/optical_flow.hpp \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/videostab.hpp \
		/usr/local/include/opencv2/videostab/stabilizer.hpp \
		/usr/local/include/opencv2/videostab/global_motion.hpp \
		/usr/local/include/opencv2/videostab/optical_flow.hpp \
		/usr/local/include/opencv2/cudaoptflow.hpp \
		/usr/local/include/opencv2/videostab/motion_core.hpp \
		/usr/local/include/opencv2/videostab/outlier_rejection.hpp \
		/usr/local/include/opencv2/cudaimgproc.hpp \
		/usr/local/include/opencv2/videostab/motion_stabilizing.hpp \
		/usr/local/include/opencv2/videostab/frame_source.hpp \
		/usr/local/include/opencv2/videostab/log.hpp \
		/usr/local/include/opencv2/videostab/inpainting.hpp \
		/usr/local/include/opencv2/videostab/fast_marching.hpp \
		/usr/local/include/opencv2/videostab/fast_marching_inl.hpp \
		/usr/local/include/opencv2/videostab/deblurring.hpp \
		/usr/local/include/opencv2/videostab/wobble_suppression.hpp \
		/usr/local/include/opencv2/videostab/ring_buffer.hpp \
		/usr/local/include/opencv2/cudaarithm.hpp \
		/usr/local/include/opencv2/cudabgsegm.hpp \
		/usr/local/include/opencv2/cudafeatures2d.hpp \
		/usr/local/include/opencv2/cudafilters.hpp \
		/usr/local/include/opencv2/cudaobjdetect.hpp \
		/usr/local/include/opencv2/cudastereo.hpp \
		/usr/local/include/opencv2/cudawarping.hpp \
		imgprofile.h \
		medianfilter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

imgprofile.o: imgprofile.cpp imgprofile.h \
		public_lib.h \
		mytuple.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/ml.hpp \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/shape.hpp \
		/usr/local/include/opencv2/shape/emdL1.hpp \
		/usr/local/include/opencv2/shape/shape_transformer.hpp \
		/usr/local/include/opencv2/shape/hist_cost.hpp \
		/usr/local/include/opencv2/shape/shape_distance.hpp \
		/usr/local/include/opencv2/stitching.hpp \
		/usr/local/include/opencv2/stitching/warpers.hpp \
		/usr/local/include/opencv2/stitching/detail/warpers.hpp \
		/usr/local/include/opencv2/core/cuda.hpp \
		/usr/local/include/opencv2/core/cuda_types.hpp \
		/usr/local/include/opencv2/core/cuda.inl.hpp \
		/usr/local/include/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/local/include/opencv2/stitching/detail/matchers.hpp \
		/usr/local/include/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/local/include/opencv2/stitching/detail/util.hpp \
		/usr/local/include/opencv2/stitching/detail/util_inl.hpp \
		/usr/local/include/opencv2/stitching/detail/camera.hpp \
		/usr/local/include/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/local/include/opencv2/stitching/detail/seam_finders.hpp \
		/usr/local/include/opencv2/stitching/detail/blenders.hpp \
		/usr/local/include/opencv2/superres.hpp \
		/usr/local/include/opencv2/superres/optical_flow.hpp \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/videostab.hpp \
		/usr/local/include/opencv2/videostab/stabilizer.hpp \
		/usr/local/include/opencv2/videostab/global_motion.hpp \
		/usr/local/include/opencv2/videostab/optical_flow.hpp \
		/usr/local/include/opencv2/cudaoptflow.hpp \
		/usr/local/include/opencv2/videostab/motion_core.hpp \
		/usr/local/include/opencv2/videostab/outlier_rejection.hpp \
		/usr/local/include/opencv2/cudaimgproc.hpp \
		/usr/local/include/opencv2/videostab/motion_stabilizing.hpp \
		/usr/local/include/opencv2/videostab/frame_source.hpp \
		/usr/local/include/opencv2/videostab/log.hpp \
		/usr/local/include/opencv2/videostab/inpainting.hpp \
		/usr/local/include/opencv2/videostab/fast_marching.hpp \
		/usr/local/include/opencv2/videostab/fast_marching_inl.hpp \
		/usr/local/include/opencv2/videostab/deblurring.hpp \
		/usr/local/include/opencv2/videostab/wobble_suppression.hpp \
		/usr/local/include/opencv2/videostab/ring_buffer.hpp \
		/usr/local/include/opencv2/cudaarithm.hpp \
		/usr/local/include/opencv2/cudabgsegm.hpp \
		/usr/local/include/opencv2/cudafeatures2d.hpp \
		/usr/local/include/opencv2/cudafilters.hpp \
		/usr/local/include/opencv2/cudaobjdetect.hpp \
		/usr/local/include/opencv2/cudastereo.hpp \
		/usr/local/include/opencv2/cudawarping.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgprofile.o imgprofile.cpp

medianfilter.o: medianfilter.cpp public_lib.h \
		mytuple.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/ml.hpp \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/shape.hpp \
		/usr/local/include/opencv2/shape/emdL1.hpp \
		/usr/local/include/opencv2/shape/shape_transformer.hpp \
		/usr/local/include/opencv2/shape/hist_cost.hpp \
		/usr/local/include/opencv2/shape/shape_distance.hpp \
		/usr/local/include/opencv2/stitching.hpp \
		/usr/local/include/opencv2/stitching/warpers.hpp \
		/usr/local/include/opencv2/stitching/detail/warpers.hpp \
		/usr/local/include/opencv2/core/cuda.hpp \
		/usr/local/include/opencv2/core/cuda_types.hpp \
		/usr/local/include/opencv2/core/cuda.inl.hpp \
		/usr/local/include/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/local/include/opencv2/stitching/detail/matchers.hpp \
		/usr/local/include/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/local/include/opencv2/stitching/detail/util.hpp \
		/usr/local/include/opencv2/stitching/detail/util_inl.hpp \
		/usr/local/include/opencv2/stitching/detail/camera.hpp \
		/usr/local/include/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/local/include/opencv2/stitching/detail/seam_finders.hpp \
		/usr/local/include/opencv2/stitching/detail/blenders.hpp \
		/usr/local/include/opencv2/superres.hpp \
		/usr/local/include/opencv2/superres/optical_flow.hpp \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/videostab.hpp \
		/usr/local/include/opencv2/videostab/stabilizer.hpp \
		/usr/local/include/opencv2/videostab/global_motion.hpp \
		/usr/local/include/opencv2/videostab/optical_flow.hpp \
		/usr/local/include/opencv2/cudaoptflow.hpp \
		/usr/local/include/opencv2/videostab/motion_core.hpp \
		/usr/local/include/opencv2/videostab/outlier_rejection.hpp \
		/usr/local/include/opencv2/cudaimgproc.hpp \
		/usr/local/include/opencv2/videostab/motion_stabilizing.hpp \
		/usr/local/include/opencv2/videostab/frame_source.hpp \
		/usr/local/include/opencv2/videostab/log.hpp \
		/usr/local/include/opencv2/videostab/inpainting.hpp \
		/usr/local/include/opencv2/videostab/fast_marching.hpp \
		/usr/local/include/opencv2/videostab/fast_marching_inl.hpp \
		/usr/local/include/opencv2/videostab/deblurring.hpp \
		/usr/local/include/opencv2/videostab/wobble_suppression.hpp \
		/usr/local/include/opencv2/videostab/ring_buffer.hpp \
		/usr/local/include/opencv2/cudaarithm.hpp \
		/usr/local/include/opencv2/cudabgsegm.hpp \
		/usr/local/include/opencv2/cudafeatures2d.hpp \
		/usr/local/include/opencv2/cudafilters.hpp \
		/usr/local/include/opencv2/cudaobjdetect.hpp \
		/usr/local/include/opencv2/cudastereo.hpp \
		/usr/local/include/opencv2/cudawarping.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o medianfilter.o medianfilter.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

